import { useState, useCallback } from 'react';
// FIX: Import missing types.
import type { TrainingActivity, TrainingModule, Trainee, Tool, QuizQuestion } from '../types';
import { Icons } from '../components/Icons';

const INITIAL_ACTIVITIES: TrainingActivity[] = [
    {
        id: 'act1',
        title: 'Angry Customer Scenario',
        category: 'Practice',
        objective: 'Train pharmacists to handle customer complaints effectively and de-escalate anger.',
        duration: 20,
        tools: 'Printed scenario cards for each participant.',
        instructions: '1. Divide trainees into pairs.\n2. Each pair takes on the role of "pharmacist" and "angry customer".\n3. The "customer" acts out a specific complaint scenario (e.g., missing medication, wrong price).\n4. The "pharmacist" must apply active listening, calming techniques, and problem-solving skills.\n5. After 7 minutes, switch roles.\n6. Finally, hold a group discussion to share experiences.',
        pharmaExample: 'A customer complains that the medication they received has side effects they were not told about.',
        groupSize: 'Small Groups',
        tags: ['role-play', 'communication', 'problem-solving'],
    },
    {
        id: 'act2',
        title: 'Two Truths and a Lie',
        category: 'Openers',
        objective: 'Build rapport and get to know each other',
        duration: 9,
        instructions: '1. Ask each participant to write two truths + one lie in the chat.\n2. Others guess the lie via poll or chat.\n3. Reveal the truth and discuss.',
        tools: 'Zoom, Mentimeter, Slido',
        pharmaExample: '"I worked on a clinical trial; I audited 20 pharmacies; I have never used Excel."',
        groupSize: 'Small Groups',
        tags: ['icebreaker', 'team-building', 'virtual-friendly'],
    },
    {
        id: 'act3',
        title: 'Case Study: Drug Interactions',
        category: 'Practice',
        objective: 'Enhance pharmacists\' ability to identify and review potential drug interactions on a prescription.',
        duration: 25,
        tools: 'Printed prescriptions with intentional drug interactions.',
        instructions: '1. Distribute case studies (prescriptions) to small groups (3-4 people).\n2. Ask each group to review the prescription and identify any potential drug interactions.\n3. The group should discuss the severity of the interaction and propose solutions (e.g., contact the doctor, advise the patient).\n4. Each group presents its findings to the rest of the trainees.',
        pharmaExample: 'Reviewing a prescription for an elderly patient taking multiple medications for chronic diseases and identifying critical interactions.',
        groupSize: 'Small Groups',
        tags: ['analytical-skills', 'case-study', 'collaboration'],
    },
    {
        id: 'act4',
        title: 'Virtual Background Stories',
        category: 'Openers',
        objective: 'Creative introductions',
        duration: 10,
        instructions: 'Participants set a Zoom background reflecting their mood/personality/topic. They share in breakout rooms (3-4 each). Some volunteer to share in plenary.',
        tools: 'Zoom',
        pharmaExample: 'A participant uses a lab background and explains they work in drug formulation.',
        groupSize: 'Both',
        tags: ['icebreaker', 'virtual-friendly', 'creativity'],
    },
    {
        id: 'act5',
        title: 'Introductory Chat Storm',
        category: 'Openers',
        objective: 'Instant engagement',
        duration: 5,
        instructions: 'Pose a question in the chat ("In one word, how do you feel about today\'s topic?"). Everyone types but waits. On signal, everyone hits Enter. Discuss themes.',
        tools: 'Zoom',
        pharmaExample: 'Q: "In one word, how do you feel about regulatory inspections?" A: Nervous, Confident.',
        groupSize: 'Big Groups',
        tags: ['quick', 'virtual-friendly', 'engagement', 'no-equipment'],
    },
    {
        id: 'act6',
        title: 'Quick Icebreaker Poll',
        category: 'Openers',
        objective: 'Fun, insightful data',
        duration: 7,
        instructions: 'Run 2–3 polls mixing personal questions with topic-related ones. Discuss surprising patterns. Link to objectives.',
        tools: 'Kahoot, Slido, Mentimeter',
        pharmaExample: 'Poll: "What\'s most challenging? R&D / Compliance / Patient Safety / Competition."',
        groupSize: 'Both',
    },
    {
        id: 'act7',
        title: 'Name + Emoji Game',
        category: 'Openers',
        objective: 'Light-hearted intros',
        duration: 6,
        instructions: 'Participants type name + emoji in chat. Facilitator connects emojis to roles.',
        tools: 'Zoom',
        pharmaExample: '"Sarah 💊 (Retail Pharmacist)"; "Ahmed 🧪 (QC)."',
        groupSize: 'Small Groups',
    },
    {
        id: 'act8',
        title: 'Show and Tell Object',
        category: 'Openers',
        objective: 'Personal connection',
        duration: 10,
        instructions: 'Ask participants to bring an object that represents their work.',
        tools: 'Zoom, Padlet',
        pharmaExample: 'Someone shows a medicine bottle to represent patient safety.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act9',
        title: 'Topic Word Cloud',
        category: 'Openers',
        objective: 'Visualize expectations',
        duration: 5,
        instructions: 'Ask: "What comes to mind when you hear [Topic]?" Display the live cloud.',
        tools: 'Mentimeter',
        pharmaExample: 'Words: Research, Patients, Compliance, Innovation, Safety.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act10',
        title: 'Mini-Debate Starter',
        category: 'Openers',
        objective: 'Spark curiosity',
        duration: 8,
        instructions: 'Introduce a statement (e.g., "Finance is only for financiers"). Breakout groups discuss for 3 min. Share back. Discuss.',
        tools: 'Zoom, Google Docs',
        pharmaExample: 'Statement: "Generic drugs are just as important as branded ones."',
        groupSize: 'Both',
    },
    {
        id: 'act11',
        title: 'Personal Goal Setting',
        category: 'Openers',
        objective: 'Clarify learning goals',
        duration: 7,
        instructions: 'Ask participants to submit one goal via a form. Share an anonymized summary. Revisit at the end of the session.',
        tools: 'Google Forms, Mentimeter',
        pharmaExample: '"I want to improve my knowledge of GMP compliance."',
        groupSize: 'Both',
    },
    {
        id: 'act12',
        title: 'Concept Mapping',
        category: 'Linking & Summarizing',
        objective: 'Connect concepts visually',
        duration: 15,
        instructions: 'Ask participants to list 4–5 key concepts from the session. Provide a shared mind-map board (Miro, Coggle, MindMeister). Have them draw connections with arrows/lines. Facilitator highlights common links and misconceptions.',
        tools: 'Miro, MindMeister',
        pharmaExample: 'Map: Drug Discovery -> Clinical Trials -> FDA Approval -> Market.',
        groupSize: 'Both',
        tags: ['visual-thinking', 'collaboration', 'review'],
    },
    {
        id: 'act13',
        title: 'Think-Pair-Share',
        category: 'Linking & Summarizing',
        objective: 'Deepen understanding',
        duration: 10,
        instructions: 'Pose a reflection question (e.g., “How does budgeting impact decision-making?”). Give 2 minutes for individual reflection (quiet thinking, jot notes). Send to breakout pairs for 3 minutes to share ideas. Return to plenary, volunteers summarize.',
        tools: 'Zoom',
        pharmaExample: 'Q: How does supply chain disruption affect patient access?',
        groupSize: 'Small Groups',
    },
    {
        id: 'act14',
        title: 'Summary Carousel',
        category: 'Linking & Summarizing',
        objective: 'Peer co-creation of summaries',
        duration: 15,
        instructions: 'Create a shared Google Doc with sections for each group. Assign each group to summarize key points from one topic. After 3 minutes, rotate groups to add/edit other sections. Continue rotation until all groups have contributed. Debrief by highlighting the final document.',
        tools: 'Google Docs, Miro',
        pharmaExample: 'Each group summarizes a section of GMP guidelines.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act15',
        title: 'Timeline Builder',
        category: 'Linking & Summarizing',
        objective: 'Show progression of events',
        duration: 10,
        instructions: 'Give participants a list of events/concepts. Teams place them on a digital timeline (Miro/Trello). Groups discuss their rationale. Facilitator reviews the final sequence.',
        tools: 'Miro, Trello',
        pharmaExample: 'Sequence: Preclinical -> Phase I -> Phase II -> Phase III -> Approval.',
        groupSize: 'Both',
    },
    {
        id: 'act16',
        title: 'Recap Quiz',
        category: 'Linking & Summarizing',
        objective: 'Check knowledge, reinforce',
        duration: 10,
        instructions: 'Prepare 5 short quiz questions. Run quiz live with Kahoot or Quizizz. Display leaderboard and review answers. Discuss misconceptions.',
        tools: 'Kahoot, Quizizz',
        pharmaExample: 'Q: Which trial phase involves healthy volunteers?',
        groupSize: 'Both',
        tags: ['quiz', 'assessment', 'engagement', 'virtual-friendly'],
    },
    {
        id: 'act17',
        title: 'Digital Posters',
        category: 'Linking & Summarizing',
        objective: 'Visual summaries',
        duration: 12,
        instructions: 'Divide participants into small groups. Ask them to create posters summarizing key learnings using Jamboard or Padlet. Share posters in plenary. Facilitator highlights connections.',
        tools: 'Jamboard, Padlet',
        pharmaExample: 'Poster: Pharmacovigilance Best Practices.',
        groupSize: 'Both',
    },
    {
        id: 'act18',
        title: 'Pairwise Explanation',
        category: 'Linking & Summarizing',
        objective: 'Reinforce by teaching',
        duration: 10,
        instructions: 'Pair participants in breakout rooms. Each explains one concept in their own words (3 min each). Switch roles. Return to plenary and debrief.',
        tools: 'Zoom',
        pharmaExample: 'One explains bioequivalence, the other stability testing.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act19',
        title: 'Linking Statements',
        category: 'Linking & Summarizing',
        objective: 'Show concept relationships',
        duration: 10,
        instructions: 'Prepare a set of related statements. Share via Padlet/Miro sticky notes. Participants drag and connect related notes. Facilitator explains correct/important links.',
        tools: 'Padlet, Miro',
        pharmaExample: 'Connect Drug Recalls -> Patient Safety -> Adverse Event Reporting.',
        groupSize: 'Both',
    },
    {
        id: 'act20',
        title: 'Group Chat Summary',
        category: 'Linking & Summarizing',
        objective: 'Capture discussion in chat',
        duration: 8,
        instructions: 'Assign one participant as scribe. During discussion, they type key points into chat. At the end, facilitator summarizes key messages aloud.',
        tools: 'Zoom, Microsoft Teams',
        pharmaExample: 'Scribe notes discussion on ethical pharma marketing.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act21',
        title: 'Analogy Builder',
        category: 'Linking & Summarizing',
        objective: 'Deepen understanding',
        duration: 10,
        instructions: 'Ask: "If this concept were a [object/animal/tool], what would it be and why?" Participants write their analogies in chat or Padlet. Facilitator reads and highlights the most insightful ones.',
        tools: 'Zoom, Padlet',
        pharmaExample: '"GMP is like a seatbelt – it prevents accidents."',
        groupSize: 'Both',
    },
    {
        id: 'act22',
        title: 'Interactive Lecture with Polls',
        category: 'Delivery',
        objective: 'Keep lecture engaging',
        duration: 25,
        instructions: 'Insert polls every 8–10 min.',
        tools: 'Mentimeter, Zoom',
        pharmaExample: 'Poll: What impacts drug pricing most?',
        groupSize: 'Big Groups',
    },
    {
        id: 'act23',
        title: 'Live Demonstration',
        category: 'Delivery',
        objective: 'Show practical use',
        duration: 18,
        instructions: 'Screen share demo.',
        tools: 'Zoom, Microsoft Teams',
        pharmaExample: 'Demo of pharmacovigilance database entry.',
        groupSize: 'Both',
    },
    {
        id: 'act24',
        title: 'Case Study Breakouts',
        category: 'Delivery',
        objective: 'Analytical thinking',
        duration: 23,
        instructions: 'Share case PDF. Break into groups to analyze. Groups submit solutions in shared doc. Debrief together.',
        tools: 'Google Docs, Zoom',
        pharmaExample: 'Case: A contaminated vaccine batch recall.',
        groupSize: 'Both',
    },
    {
        id: 'act25',
        title: 'Guided Discussion',
        category: 'Delivery',
        objective: 'Group sense-making',
        duration: 18,
        instructions: 'Pose 2–3 key questions. Capture answers on Padlet. Summarize themes at end.',
        tools: 'Padlet',
        pharmaExample: '“What’s the biggest pharma supply chain challenge?”',
        groupSize: 'Both',
    },
    {
        id: 'act26',
        title: 'Role-Play Demo',
        category: 'Delivery',
        objective: 'Experiential learning',
        duration: 18,
        instructions: 'Choose 2–3 volunteers to act out a scenario live. Observers take notes. Debrief as a group.',
        tools: 'Zoom',
        pharmaExample: 'Rep explains new oncology drug to doctor.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act27',
        title: 'Collaborative Docs',
        category: 'Delivery',
        objective: 'Build knowledge',
        duration: 23,
        instructions: 'Provide shared doc divided into sections. Assign each group a section. Present results back in plenary.',
        tools: 'Google Docs',
        pharmaExample: 'Drug Development Challenges in Emerging Markets.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act28',
        title: 'Virtual Gallery Walk',
        category: 'Delivery',
        objective: 'Compare outputs',
        duration: 18,
        instructions: 'Assign groups to create posters/slides. Upload to Jamboard. Others browse and comment.',
        tools: 'Jamboard',
        pharmaExample: 'Posters: Types of clinical trial designs.',
        groupSize: 'Both',
    },
    {
        id: 'act29',
        title: 'Fishbowl Discussion',
        category: 'Delivery',
        objective: 'Deep group discussion',
        duration: 23,
        instructions: 'Assign 4 participants to inner circle. Others observe. Rotate after 5–7 min. Debrief with whole group.',
        tools: 'Zoom',
        pharmaExample: 'Debate: Should pharma focus on rare diseases?',
        groupSize: 'Big Groups',
    },
    {
        id: 'act30',
        title: 'Interactive Polling',
        category: 'Delivery',
        objective: 'Check understanding',
        duration: 10,
        instructions: 'Mix polls (knowledge, opinions, predictions). Discuss patterns before continuing.',
        tools: 'Mentimeter, Slido',
        pharmaExample: 'Q: Top cause of drug recalls?',
        groupSize: 'Both',
    },
    {
        id: 'act31',
        title: 'Video Case Analysis',
        category: 'Delivery',
        objective: 'Visual engagement',
        duration: 18,
        instructions: 'Play short video. Break into groups to discuss. Return and share insights.',
        tools: 'YouTube, Zoom',
        pharmaExample: 'Video: COVID-19 vaccine approval journey.',
        groupSize: 'Both',
    },
    {
        id: 'act32',
        title: 'Emoji Check-In',
        category: 'Energizers',
        objective: 'Mood check + energy',
        duration: 3,
        instructions: 'Ask: "Share your current mood with just one emoji." Everyone posts in chat simultaneously. Read aloud some interesting/funny ones. Link back: "Great to see the energy! Let\'s dive into the next part."',
        tools: 'Zoom',
        pharmaExample: '🤗 (after GMP), 💪 (after compliance talk).',
        groupSize: 'Both',
    },
    {
        id: 'act33',
        title: 'Virtual Dance Break',
        category: 'Energizers',
        objective: 'Boost energy & fun',
        duration: 4,
        instructions: 'Share an upbeat song via Zoom audio. Encourage participants to move, clap, or even dance on camera. Keep it light and optional. End with applause or thumbs up reactions.',
        tools: 'Zoom, YouTube',
        pharmaExample: 'Play instrumental upbeat music.',
        groupSize: 'Big Groups',
        tags: ['fun', 'movement', 'quick', 'virtual-friendly'],
    },
    {
        id: 'act34',
        title: 'Mini Kahoot Quiz',
        category: 'Energizers',
        objective: 'Fun + review',
        duration: 6,
        instructions: 'Prepare 3-5 quick, light questions (fun facts, session content, trivia). Share Kahoot code and let participants join. Run quiz live with leaderboard. Congratulate top scorers.',
        tools: 'Kahoot, Quizizz',
        pharmaExample: 'Q: What\'s Phase IV trial called?',
        groupSize: 'Both',
    },
    {
        id: 'act35',
        title: 'Charades (Topic)',
        category: 'Energizers',
        objective: 'Fun application',
        duration: 9,
        instructions: 'Prepare a list of training-related words. Ask volunteers to act out silently on camera. Others type guesses in chat. Rotate until several people have played.',
        tools: 'Zoom',
        pharmaExample: 'Act out tablet compression -> team guesses.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act36',
        title: 'Quick Draw Challenge',
        category: 'Energizers',
        objective: 'Spark creativity',
        duration: 6,
        instructions: 'Give participants a prompt (e.g., "Draw how you feel about today\'s topic"). Allow 1-2 minutes to draw on paper or Jamboard. Share by holding paper up to camera or uploading digitally.',
        tools: 'Jamboard',
        pharmaExample: 'Prompt: "Draw pharma innovation."',
        groupSize: 'Both',
    },
    {
        id: 'act37',
        title: 'Scavenger Hunt',
        category: 'Energizers',
        objective: 'Movement & fun',
        duration: 8,
        instructions: 'Give a prompt: "Find something red" or "Bring an object you use daily for work." Give 1-2 minutes. Participants return and show on camera. Celebrate creative finds.',
        tools: 'Zoom',
        pharmaExample: 'Show something that represents patient safety.',
        groupSize: 'Both',
    },
    {
        id: 'act38',
        title: 'Emoji Story Chain',
        category: 'Energizers',
        objective: 'Build creativity',
        duration: 6,
        instructions: 'Start a story with emojis in chat (e.g., "👨‍⚕️💊➡️😊"). Each participant adds one emoji to continue the story. Read the final chain aloud as a "story."',
        tools: 'Zoom',
        pharmaExample: 'Story: 💊➡️😋➡️🚚➡️🏥➡️👨‍⚕️ (medicine to patient).',
        groupSize: 'Big Groups',
    },
    {
        id: 'act39',
        title: 'Breakout Labs',
        category: 'Practice',
        objective: 'Apply learning',
        duration: 23,
        tools: 'Google Docs, Zoom',
        instructions: 'Provide a challenge. Breakouts work on it using shared docs. Each group presents 2-min summary.',
        pharmaExample: 'Solve: High dropout in clinical trial – suggest solutions.',
        groupSize: 'Both',
    },
    {
        id: 'act40',
        title: 'Role-Play Scenarios',
        category: 'Practice',
        objective: 'Practice skills',
        duration: 18,
        tools: 'Google Docs, Zoom',
        instructions: 'Groups role-play Provide scenarios. Assign roles in breakout groups. Rotate roles. Debrief together.',
        pharmaExample: 'Regulatory agency vs pharma company approval meeting.',
        groupSize: 'Small Groups',
        tags: ['role-play', 'communication', 'skill-practice'],
    },
    {
        id: 'act41',
        title: 'Simulation Game',
        category: 'Practice',
        objective: 'Practice decision-making',
        duration: 35,
        tools: 'Forio, SimulTrain',
        instructions: 'Use online simulation platform. Teams make choices. Debrief consequences.',
        pharmaExample: 'Allocate R&D budget for new drug pipeline.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act42',
        title: 'Peer Coaching Triads',
        category: 'Practice',
        objective: 'Peer learning',
        duration: 20,
        tools: 'Zoom',
        instructions: 'Groups of 3. Rotate roles (practitioner, coach, observer). Provide feedback template.',
        pharmaExample: 'Challenge: Improving compliance in sales reps.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act43',
        title: 'Digital Escape Room',
        category: 'Practice',
        objective: 'Problem-solving + fun',
        duration: 28,
        tools: 'Genially, Google Forms',
        instructions: 'Teams solve online puzzles linked to content. First team to "escape" wins.',
        pharmaExample: 'Puzzles: Regulatory acronyms, GMP standards.',
        groupSize: 'Both',
    },
    {
        id: 'act44',
        title: 'Challenge Projects',
        category: 'Practice',
        objective: 'Apply knowledge',
        duration: 35,
        tools: 'Miro, Google Docs',
        instructions: 'Assign workplace challenge. Groups brainstorm and present solutions.',
        pharmaExample: 'Plan to reduce counterfeit drugs in Africa.',
        groupSize: 'Big Groups',
    },
    {
        id: 'act45',
        title: 'Mistake Recovery',
        category: 'Practice',
        objective: 'Learn from failure',
        duration: 23,
        tools: 'Zoom',
        instructions: 'Provide “failed” scenario. Teams analyze and suggest recovery. Share insights in plenary.',
        pharmaExample: 'Product launch failed due to poor forecasting.',
        groupSize: 'Both',
    },
    {
        id: 'act46',
        title: 'Peer Teaching',
        category: 'Practice',
        objective: 'Reinforce learning',
        duration: 18,
        tools: 'Flipgrid, Zoom',
        instructions: 'Assign each participant a concept. They teach it briefly to peers. Peers ask questions.',
        pharmaExample: 'Teach: drug labeling rules, bioequivalence, pharmacovigilance.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act47',
        title: 'Reflection Circle',
        category: 'Closing',
        objective: 'Capture key insights',
        duration: 6,
        instructions: 'Ask: "Type one key takeaway from today\'s session." Everyone posts in chat. Facilitator highlights themes and surprising insights.',
        tools: 'Zoom',
        pharmaExample: '"Patient safety must guide every decision."',
        groupSize: 'Both',
    },
    {
        id: 'act48',
        title: 'Commitment Board',
        category: 'Closing',
        objective: 'Accountability',
        duration: 9,
        instructions: 'Open a Jamboard/Padlet with a "commitment wall." Each participant posts one action they will apply. Read aloud a few commitments. Optionally take a screenshot to revisit later.',
        tools: 'Padlet, Jamboard',
        pharmaExample: '"I will update our GMP checklist weekly."',
        groupSize: 'Both',
    },
    {
        id: 'act49',
        title: 'One-Minute Paper',
        category: 'Closing',
        objective: 'Reflection & evaluation',
        duration: 5,
        instructions: 'Share Google Form with prompt: "What is your key insight from today?" Participants write short reflections. Facilitator thanks them and promises to share a summary later.',
        tools: 'Google Forms',
        pharmaExample: '"Main insight: role of Phase IV monitoring."',
        groupSize: 'Both',
    },
    {
        id: 'act50',
        title: 'Appreciation Round',
        category: 'Closing',
        objective: 'End with positivity',
        duration: 5,
        instructions: 'Ask: "Type one appreciation for a peer or the group in chat." Everyone posts at the same time. Read a few aloud.',
        tools: 'Zoom',
        pharmaExample: '"Thanks to Ahmed for sharing QA experience."',
        groupSize: 'Both',
    },
    {
        id: 'act51',
        title: 'Action Planning',
        category: 'Closing',
        objective: 'Translate learning',
        duration: 9,
        instructions: 'Ask participants to write 3 concrete steps they will take after training. Collect via Padlet or shared doc. Highlight a few strong examples.',
        tools: 'Google Docs, Padlet',
        pharmaExample: '1. Revise protocols 2. Train team 3. Review compliance data.',
        groupSize: 'Both',
    },
    {
        id: 'act52',
        title: 'Virtual Graduation',
        category: 'Closing',
        objective: 'Celebrate completion',
        duration: 8,
        instructions: 'Share upbeat music. Display a "Congratulations" slide. Optionally share digital certificates. Take a group screenshot with everyone waving.',
        tools: 'Zoom, Canva',
        pharmaExample: '"Congratulations Pharma Leaders!"',
        groupSize: 'Big Groups',
    },
    {
        id: 'act53',
        title: 'Reflection Videos',
        category: 'Closing',
        objective: 'Personal reflection',
        duration: 11,
        instructions: 'Ask participants to record a 1-min reflection video. Use Flipgrid/Loom to upload. Encourage them to watch peers\' videos.',
        tools: 'Flipgrid, Loom',
        pharmaExample: '"I learned ethical marketing is key to trust."',
        groupSize: 'Both',
    },
    {
        id: 'act54',
        title: 'Resource Marketplace',
        category: 'Closing',
        objective: 'Share useful links',
        duration: 6,
        instructions: 'Share a Google Doc titled "Resources." Ask participants to paste 1 useful link or tool related to the topic. Make the doc available after session.',
        tools: 'Google Docs',
        pharmaExample: 'WHO GMP guideline, FDA site.',
        groupSize: 'Both',
    },
    {
        id: 'act55',
        title: 'Follow-Up Planning',
        category: 'Closing',
        objective: 'Accountability post-training',
        duration: 10,
        instructions: 'Pair participants in breakout rooms. Ask them to share their action plan and agree to follow up in 1 week. Collect partner names in chat.',
        tools: 'Zoom',
        pharmaExample: 'Pair agrees to follow up on compliance audit steps.',
        groupSize: 'Small Groups',
    },
    {
        id: 'act56',
        title: 'Word Cloud Takeaway',
        category: 'Closing',
        objective: 'Visual summary',
        duration: 5,
        instructions: 'Open a Mentimeter word cloud. Ask: "Enter one word that captures today\'s learning." Display live cloud and discuss.',
        tools: 'Mentimeter',
        pharmaExample: 'Words: Compliance, Safety, Patients, Innovation.',
        groupSize: 'Big Groups',
    }
];

const INITIAL_TOOLS: Tool[] = [
    {
        id: 'tool1',
        name: 'Zoom',
        description: 'A video conferencing platform for hosting virtual meetings, webinars, and training sessions.',
        useCase: 'Essential for conducting any live virtual training. Use its features like breakout rooms for small group practice, polls for instant feedback, and chat for quick engagement.',
        quickStart: '1. Create a free account on zoom.us.\n2. Schedule a new meeting to get a link.\n3. Share the link with participants.\n4. Use the controls at the bottom to manage participants, share your screen, and launch polls or breakout rooms.',
        icon: Icons.video,
        category: 'Communication',
    },
    {
        id: 'tool2',
        name: 'Padlet',
        description: 'A digital canvas that allows users to post notes, images, and links on a shared wall.',
        useCase: 'Excellent for brainstorming, collecting ideas, or as a "commitment wall". It allows everyone to contribute simultaneously and see each other\'s ideas, making collaboration visual and engaging.',
        quickStart: '1. Sign up for a free account at padlet.com.\n2. Click "Make a Padlet" and choose a format (like Wall or Shelf).\n3. Share the link in the Zoom chat.\n4. Participants can double-click anywhere to add a post.',
        icon: Icons.layoutGrid,
        category: 'Collaboration',
    },
    {
        id: 'tool3',
        name: 'Mentimeter',
        description: 'An interactive presentation tool that lets you engage your audience with live polls, word clouds, Q&As, and quizzes.',
        useCase: 'Perfect for icebreakers (word clouds), checking understanding (multiple-choice polls), and gathering anonymous feedback. It keeps the energy high and gives everyone a voice.',
        quickStart: '1. Create an account at mentimeter.com.\n2. Create a new presentation and add slides (e.g., Word Cloud, Multiple Choice).\n3. Click "Present" and share the voting code/link with your audience.\n4. Participants vote on their phones, and results appear live on your screen.',
        icon: Icons.barChart,
        category: 'Presentation',
    },
    {
        id: 'tool4',
        name: 'Google Docs',
        description: 'A collaborative word processor that allows multiple users to edit a document in real-time.',
        useCase: 'Ideal for activities where groups need to co-create content, such as summarizing key points, documenting solutions to a case study, or building a shared resource list.',
        quickStart: '1. Create a new document at docs.google.com.\n2. Click the "Share" button and set permissions to "Anyone with the link can edit".\n3. Copy the link and share it with participants.\n4. You can see everyone typing live in the document.',
        icon: Icons.fileText,
        category: 'Collaboration',
    },
    {
        id: 'tool5',
        name: 'Kahoot!',
        description: 'A game-based learning platform that makes it easy to create, share, and play fun learning games or trivia quizzes.',
        useCase: 'A fantastic way to energize the group, review key concepts in a fun and competitive way, or run a quick knowledge check. The music and leaderboard add to the excitement.',
        quickStart: '1. Sign up at kahoot.com.\n2. Create a new "kahoot" and add your questions.\n3. Start the game and share your screen in Zoom.\n4. Participants join using a PIN on their phones and compete.',
        icon: Icons.gamepad,
        category: 'Assessment',
    },
     {
        id: 'tool6',
        name: 'Miro',
        description: 'An online collaborative whiteboard platform that enables distributed teams to work effectively together.',
        useCase: 'Perfect for complex visual activities like concept mapping, timeline building, or strategic planning. Its infinite canvas allows for deep, structured collaboration.',
        quickStart: '1. Create a free account at miro.com.\n2. Choose a template (e.g., Mind Map) or start with a blank board.\n3. Invite collaborators by sharing the board link.\n4. Use sticky notes, shapes, and arrows to visualize ideas.',
        icon: Icons.gitBranch,
        category: 'Collaboration',
    },
     {
        id: 'tool7',
        name: 'Jamboard',
        description: 'A digital interactive whiteboard developed by Google, part of the Google Workspace suite.',
        useCase: 'A simple and effective tool for digital posters, quick brainstorming sessions, or collecting feedback on sticky notes. It\'s less complex than Miro, making it great for quick tasks.',
        quickStart: '1. Go to jamboard.google.com.\n2. Create a new "Jam".\n3. Share the link with edit permissions.\n4. Participants can add sticky notes, draw, or add images to the board.',
        icon: Icons.edit,
        category: 'Collaboration',
    },
    {
        id: 'tool8',
        name: 'Flipgrid',
        description: 'A video discussion platform where educators can post topics and students respond with short videos.',
        useCase: 'Excellent for personal reflection activities where participants can record their thoughts asynchronously. It encourages deeper, more considered responses than a live chat.',
        quickStart: '1. Create an educator account at flipgrid.com.\n2. Create a "Group" for your training and add a "Topic".\n3. Share the join code or link.\n4. Participants can then record and submit their video responses.',
        icon: Icons.video,
        category: 'Communication',
    }
];


// FIX: Add mock data for modules.
const INITIAL_MODULES: TrainingModule[] = [
    {
        id: 'mod1',
        title: 'Principles of Clinical Pharmacy',
        category: 'Pharmaceutical Knowledge',
        description: 'A foundational module covering the key concepts in clinical pharmacy.',
        content: 'Content covers the history of pharmacy, the role of the pharmacist, medication review, and common drug interactions.',
        quiz: [
// FIX: The QuizQuestion type expects `correctAnswer` to be a string, not `correctAnswerIndex`. Also added missing `type` property.
            { question: 'What is the primary role of a clinical pharmacist?', type: 'multiple-choice', options: ['Selling drugs', 'Ensuring the safe and effective use of medications', 'Inventory management', 'Marketing'], correctAnswer: 'Ensuring the safe and effective use of medications' }
        ]
    },
    {
        id: 'mod2',
        title: 'Effective Communication Skills',
        category: 'Soft Skills',
        description: 'Developing communication skills for interacting with patients and colleagues.',
        content: 'The module includes techniques for active listening, patient counseling, and handling difficult situations.',
        quiz: []
    }
];

// FIX: Add mock data for trainees.
const INITIAL_TRAINEES: Trainee[] = [
    { id: 'trn1', name: 'Ahmed Mahmoud', employeeId: 'EMP001', branch: 'Riyadh Branch', role: 'Pharmacist', completedModules: ['mod1'] },
    { id: 'trn2', name: 'Fatima Al-Zahra', employeeId: 'EMP002', branch: 'Jeddah Branch', role: 'Pharmacy Assistant', completedModules: [] },
    { id: 'trn3', name: 'Ali Hassan', employeeId: 'EMP003', branch: 'Riyadh Branch', role: 'Trainee Pharmacist', completedModules: ['mod1', 'mod2'] },
];


export const useMockData = () => {
  const [activities] = useState<TrainingActivity[]>(INITIAL_ACTIVITIES);
  const [tools] = useState<Tool[]>(INITIAL_TOOLS);
  // FIX: Add state for modules and trainees.
  const [modules, setModules] = useState<TrainingModule[]>(INITIAL_MODULES);
  const [trainees, setTrainees] = useState<Trainee[]>(INITIAL_TRAINEES);

  // FIX: Add handlers for modules to support Modules component.
  const addModule = useCallback((newModule: Omit<TrainingModule, 'id'>) => {
    setModules(prev => [...prev, { ...newModule, id: `mod${Date.now()}` }]);
  }, []);

  const updateModule = useCallback((updatedModule: TrainingModule) => {
    setModules(prev => prev.map(m => m.id === updatedModule.id ? updatedModule : m));
  }, []);


  // FIX: Return modules and trainees from the hook.
  return { activities, tools, modules, trainees, addModule, updateModule };
};